name: CI Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du code
        uses: actions/checkout@v2

      - name: Installation de JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"

      - name: Construction et tests du backend
        run: |
          cd back
          ./mvnw clean package
          ./mvnw test
          ./mvnw jacoco:report
